### ISSUE TITLE
Animated WebP decoding error

### ISSUE THREAD

**Issue by rrconkle** [image-rs/image#2320] opened 2024-09-10 03:55 UTC
## Expected

![derpy_cloud_right](https://github.com/user-attachments/assets/55fca918-3023-43f0-81a5-ca881ef5883a)
Github doesn't support WebP, so this a GIF. 

The WebP used was gotten using `gif2webp`
```shell
gif2webp derpy_cloud_right.gif -o derpy_cloud_right.webp
```
The original gif can be found [here](https://github.com/RoosterDragon/Desktop-Ponies/blob/master/Content/Ponies/Derpy%20Hooves/derpy_cloud_right.gif)

## Actual behaviour

![derpy_cloud_right webp](https://github.com/user-attachments/assets/65e99305-2b2f-480f-af22-6a1bea8f3bd0)

This was made with this code
```rust
use std::fs::File;
use std::io::Cursor;

use image::codecs::gif::{GifEncoder, Repeat};
use image::codecs::webp::WebPDecoder;
use image::AnimationDecoder;

fn main() {
    let path = String::from("derpy_cloud_right.webp");

    let decoder = WebPDecoder::new(Cursor::new(std::fs::read(path.clone()).unwrap())).unwrap();
    let frames = decoder.into_frames();

    let file = File::create(path + ".gif").unwrap();
    let mut encoder = GifEncoder::new(file);
    encoder.set_repeat(Repeat::Infinite).unwrap();

    encoder.try_encode_frames(frames).unwrap();
}
```

The original shows up fine on everything else I tested. Similar behavior happens with other images in the repository linked above

**Comment by Shnatsel** [comment] 2024-09-11 11:03
Could you also attach the input WebP image so the issue could be reproduced? You can compress it with zip or gzip so that it could be uploaded to Github.

**Comment by rrconkle** [comment] 2024-09-11 21:26
Here's a zip

[derpy_cloud_right.zip](https://github.com/user-attachments/files/16970570/derpy_cloud_right.zip)

**Comment by Shnatsel** [comment] 2024-09-13 13:42
It looks like the WebP animation decoder just returns the underlying frames without compositing them properly, accounting for the frame offsets. We already have the compositing implemented for GIF and probably APNG, maybe we should just split the compositor into a shared code and refactor everything to use it.

**Comment by fintelia** [comment] 2024-09-14 01:19
This may be a duplicate of https://github.com/image-rs/image-webp/issues/84. Which is a good reminder that we're overdue for a new release that includes that fix...

In any case, `image-webp`'s animation decoding is severely under-tested. There's a lot of different codepaths through the  compositing logic and many of them aren't tested by any of the sample images.

**Comment by Shnatsel** [comment] 2024-09-19 07:10
While the linked PR is an improvement, the issue still isn't fully fixed. The provided WebP image still isn't decoded entirely correctly.

**Comment by Juliapixel** [comment] 2024-09-20 00:04
> While the linked PR is an improvement, the issue still isn't fully fixed. The provided WebP image still isn't decoded entirely correctly.

i wasn't entirely sure what you meant by that, so i ran both the gif produced on my PR and the provided expected result in this issue through ffmpeg to try and find any differences but was unable to

<details>
<summary>101 lines of PSNR data for each frame</summary>

<sub>(i even hashed the files to make sure i hadn't downloaded the same file twice)</sub>

```
n:1 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:2 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:3 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:4 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:5 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:6 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:7 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:8 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:9 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:10 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:11 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:12 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:13 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:14 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:15 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:16 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:17 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:18 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:19 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:20 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:21 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:22 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:23 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:24 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:25 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:26 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:27 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:28 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:29 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:30 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:31 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:32 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:33 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:34 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:35 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:36 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:37 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:38 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:39 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:40 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:41 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:42 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:43 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:44 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:45 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:46 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:47 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:48 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:49 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:50 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:51 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:52 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:53 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:54 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:55 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:56 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:57 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:58 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:59 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:60 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:61 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:62 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:63 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:64 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:65 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:66 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:67 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:68 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:69 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:70 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:71 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:72 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:73 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:74 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:75 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:76 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:77 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:78 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:79 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:80 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:81 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:82 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:83 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:84 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:85 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:86 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:87 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:88 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:89 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:90 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:91 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:92 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:93 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:94 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:95 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:96 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:97 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:98 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:99 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:100 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf 
n:101 mse_avg:0.00 mse_r:0.00 mse_g:0.00 mse_b:0.00 mse_a:0.00 psnr_avg:inf psnr_r:inf psnr_g:inf psnr_b:inf psnr_a:inf
```

</details>

command used: `ffmpeg -i expected.gif -i pr_101.gif -lavfi "[0:v][1:v]psnr=stats_file=stats.txt" -f null -`

please do let me know if you can find any problems i missed and i'll see if i can fix them

**Comment by Shnatsel** [comment] 2024-09-20 08:07
Ah, I'm sorry, I misunderstood [this message](https://github.com/image-rs/image-webp/pull/110#issuecomment-2357565160).

Thanks for the fix! Closing as completed.

**Closed by Shnatsel** 2024-09-20 08:07 UTC
Labels: kind: bug, kind: incorrect
