### ISSUE TITLE
A few errors in jpeg decoder

### ISSUE THREAD

**Issue by nstoddard** [image-rs/image#209] opened 2014-12-20 22:08 UTC
I tested some images and most are decoded properly, but a few have problems. I've uploaded five of them at https://mega.co.nz/#!KlQXHZDB!rvUlvg4ey7NEZcpYXiFcPsodwliLKAsybgLQboea9Z8, along with notes about what's wrong.

**Comment by forgemo** [comment] 2015-01-08 16:29
I think I stumbled over the simliar issue. The attached 'out.jpg' was generated with the following code from the also attached 'in.jpg'. You can clearly see some visual errors by comparing both images.

    extern crate imagerit;
    use std::io::File;
    
    fn main() {
	let img = image::open(&Path::new("in.jpg")).unwrap();
	let fout = File::create(&Path::new("out.jpg")).unwrap();
	let _    = img.save(fout, image::JPEG);
    }

Since I'm just opening the image and saving saving it back to disk any visual changes are probably encoding/decoding errors.

![Uploading in.jpg . . .]()
![Uploading out.jpg . . .]()

**Comment by nwin** [comment] 2015-03-12 13:43
There is something wrong in entropy.rs line 149. The wrapping add should not be necessary

**Comment by waddlesplash** [comment] 2015-10-12 22:36
@nwin: You said a while ago you had an offline WIP that fixed a lot of this; has that gone anywhere?

**Comment by nwin** [comment] 2015-10-17 06:20
@waddlesplash unfortunately not, I’m not having much time at the moment.

Since my WIP-version is a complete rewrite of the decoder in order to support streaming and progressive images it’s not easy to patch this issue since I’m not sure about the cause, I just know I don’t see it with my new decoder. But I have the strong suspicion that it might have something to to with the size of the image and how it is divided into blocks.

**Comment by nathanaeljones** [comment] 2016-01-14 18:11
@nwin Is your WIP version anywhere that we could contribute to? I'm very interested in a robust & fast jpeg implementation, and I might be able to support a portion of the development.

**Comment by nwin** [comment] 2016-01-15 10:27
Thank you for your offer, you're right I shouldn't let it rot on my HDD. I think should be able to make my repo public within a week.

**Comment by nwin** [comment] 2016-03-05 14:24
@nathanaeljones a bit late, but as promised: https://github.com/nwin/rust-jpeg

**Comment by philipc** [comment] 2016-05-31 06:55
This appears to have been fixed by #513 . The original link no longer works, but the attached in.jpg looks okay to me now.

**Comment by nathanaeljones** [comment] 2016-05-31 16:23
@nwin I forgot to thank you for uploading that! I've been working on other parts of [Imageflow](https://github.com/imazen/imageflow) (and getting [tomorrow's Kickstarter prepped](https://www.imageflow.io)!), but Rust implementations of the codecs are high on my priority list.

**Comment by HeroicKatora** [comment] 2019-04-23 22:48
This has been inactive for a while, and as far as I can gather it is fixed? Closing.

**Closed by HeroicKatora** 2019-04-23 22:48 UTC
Labels: bug, help wanted
