### ISSUE TITLE
Avif and webp recognition is bugged

### ISSUE THREAD

**Issue by installgentoo** [image-rs/image#1647] opened 2022-01-12 03:37 UTC
image v0.23.14

## Expected

Avif/webp should work

## Actual behaviour

Format not recognised on images of odd size

## Reproduction steps

Convert image to avif with imagemagick, use libaom backbend for libheif. You get an apparently valid file which begins with 0x00 0x00 0x00 0x1C 0x66 0x74 0x79 0x70 0x61 0x76 0x69 0x66 
Magic bytes for avif are (b"\0\0\0 ftypavif", ImageFormat::Avif), and space is 0x20
You can already see the issue. We need another variant of avif with fileseparator in palce of space.

**Comment by installgentoo** [comment] 2022-01-12 05:00
Moreover mp4parse fails at parsing valid avif

an example file https://github.com/installgentoo/assorted_curiosities/blob/master/trash/ortodox_grafix.avif
properly displayed by firefox, imagemagick and geeqie.

**Comment by installgentoo** [comment] 2022-01-12 06:23
also dav1d_get_picture() returns 0 on that image, even though content is parsed properly.

**Comment by installgentoo** [comment] 2022-01-12 06:45
// Cross-correlate pixel format with planes and alignment.
    // wrapping_sub is wanted. If num_planes is 0, this turns in a very big number that
    // still represents an invalid number of planes.
    let last_src_plane = src_format.num_planes.wrapping_sub(1);
    if !pixel_format::is_compatible(src_pixel_format, width, height, last_src_plane) {
        return Err(ErrorKind::InvalidValue);
    }

specifically fails on this

**Comment by installgentoo** [comment] 2022-01-12 09:06
Okay i've debugged a bit more, and removing that check at dcv-color-primitives-0.1.16/src/lib.rs:827 makes my avifs load correctly.

Could some actual developer help me figure out where the last_src_plane(i suspect?) is set incorrectly? This is something in image crate methinks.

**Comment by installgentoo** [comment] 2022-04-14 10:38
On top of that dcv issue dav1d 1.0.0 seems to just break avif support. Apparently you have to flush something somewhere now.

**Comment by HeroicKatora** [comment] 2022-04-14 10:50
> On top of that dcv issue dav1d 1.0.0 seems to just break avif support

Do you happen to have a reproduction? I suspect we should do a call to `primary_decoder.flush()?;` here:
https://github.com/image-rs/image/blob/master/src/codecs/avif/decoder.rs#L40-L41

**Comment by installgentoo** [comment] 2022-04-14 10:53
I'm actively trying to debug.

You can grab the test.avif image from my second post and try opening it for yourself.

**Comment by installgentoo** [comment] 2022-04-14 10:57
You know, i have no idea. It's just error -11 from get_picture, after apparently being parsed correctly. And dcv doesn't seem to be involved? Though i faintly remember error -11 last time, because dcv returned empty slice.

**Comment by installgentoo** [comment] 2022-04-14 11:08
You can try loading the provided image and seeing for yourself, if you understand the intricacies of avif parsing.

**Comment by installgentoo** [comment] 2022-04-14 11:13
Here's what libheif is doing https://github.com/strukturag/libheif/blob/0f8496f22d284e1a69df12fe0b72f375aed31315/libheif/heif_decoder_dav1d.cc

And libheif definitely works with imagemagick and dav1d 1.0.0

**Comment by HeroicKatora** [comment] 2022-04-14 11:17
https://github.com/strukturag/libheif/blob/0f8496f22d284e1a69df12fe0b72f375aed31315/libheif/heif_decoder_dav1d.cc#L178-L183

Huh. Thanks, good pointer.

**Comment by installgentoo** [comment] 2022-04-14 11:41
```
#if EPERM > 0
#define DAV1D_ERR(e) (-(e)) ///< Negate POSIX error code.
#else
#define DAV1D_ERR(e) (e)
#endif
```

This is in dav1d. So apparently -11 is EAGAIN

**Comment by installgentoo** [comment] 2022-04-14 11:51
Alright, first of all - yes, yes it is. -11 is EAGAIN. I just did 
```
			let mut ret = -11;

			while ret == -11 {
				ret = dav1d_get_picture(self.dec, &mut pic);
			}
```

in dav1d crate, and that just works. I dunno what's actually supposed to be happening there, whether you have to resend like libheif, or how to define dav1d's EAGAIN properly.

Secondly, yes, dcv issue is still there.

**Comment by fabiosky** [comment] 2022-05-17 09:50
I see that the image size passed to dcv color primitives is  288x285. The height is not a multiple of two, and that case is not supported for the I420 source pixel format. 
See https://docs.rs/dcv-color-primitives/latest/dcv_color_primitives/fn.convert_image.html, 
> [InvalidValue](https://docs.rs/dcv-color-primitives/latest/dcv_color_primitives/enum.ErrorKind.html#variant.InvalidValue) if source or destination image formats have a number of planes which is not compatible with their pixel formats

Thus, it is the root cause generating the `InvalidValue`. Obviously disabling the check will cause the color conversion to happen, but causes undefined behaviour (maybe visual seams) in the lower horizontal image border.

If you pass, for example, a 288x284 image, the conversion will succeed.
About planes and strides, everything is passed correctly in the `read_image`.

**Comment by installgentoo** [comment] 2022-05-17 09:53
we should add an empty line, then?(and remove it from decoded image)

**Comment by fabiosky** [comment] 2022-05-17 10:10
I opened https://github.com/aws/dcv-color-primitives/issues/65 to track dcv color primitives action items.
Would take a while, in the meantime, the procedure to handle the case is the following:

Assuming your luma plane (y) has original dimensions `width, height`:

* If `width` not a multiple of two, need to duplicate the rightmost column to get `W = w + 1` which becomes a multiple of two
* The same for `height` applies, duplicate the uppermost row to get  `H = h + 1` which becomes a multiple of two.

For the chroma planes (u, v) [**note**: their size could be different than luma one!]

* Check if the plane width is exactly `W / 2`. If not, duplicate the rightmost plane column.
* Do the same for plane height, should be `H / 2`, otherwise duplicate the uppermost plane row.

Color conversion has to happen passing `W, H` (not the original dimensions.

You will get a `W, H` rgb image. Obvously you may want to crop the rightmost column and uppermost row depending on the match on original `width, height`

**Comment by installgentoo** [comment] 2022-05-19 15:21
@fabiosky how do you actually duplicate columns? the file content is magic.

btw this also affects webp

**Comment by FlareFlo** [comment] 2023-04-13 17:41
Still occurs with `Decoding(DecodingError { format: Exact(Avif), underlying: Some(Error(-11)) })` on `0.24.6`. There was a cheap "hack" mentioned in [the tracking Dav1d issue](https://github.com/rust-av/dav1d-rs/issues/64#issue-1204439978), is it possible to adopt said fix until the underlying issue is fixed?

**Comment by FlareFlo** [comment] 2023-04-14 16:07
It might generally be a good idea to update dAV1d-rs, as the current version used by `image` was released [more than a full year ago](https://github.com/rust-av/dav1d-rs/commit/e3aba32db882372730cb6efb724a9f77ce55b7d5) (6.0 => 9.3). It appears that said [issue](https://github.com/rust-av/dav1d-rs/issues/72) was addressed in [this commit](https://github.com/rust-av/dav1d-rs/commit/0313f7dadd8cdb6311c971dfa510b5524f68fc7c).

**Closed** 2024-11-04 09:58 UTC
Labels: kind: bug, topic: formats, help wanted
