### ISSUE TITLE
Some time will occur `Err` value: Decoding(DecodingError { format: Exact(Png), underlying: Some(Format("unexpected EOF"))

### ISSUE THREAD

**Issue by adminSxs** [image-rs/image#1282] opened 2020-07-18 09:00 UTC

**Comment by HeroicKatora** [comment] 2020-07-18 13:17
This error tells you that the library thinks the image is too short to be valid. Without any example of a failing image, this is completely non-actionable.

**Comment by HeroicKatora** [comment] 2021-02-13 18:01
Closing because it has no reproduction or other information that could allow us to even validate this issue.

**Closed by HeroicKatora** 2021-02-13 18:01 UTC
Labels: question

**Comment by louy2** [comment] 2022-02-13 22:56
I have hit this error on an Discord avatar. Unfortunately I neglected to preserve the image due to privacy.
