### ISSUE TITLE
Dual license under Apache/MIT?

### ISSUE THREAD

**Issue by bvssvni** [image-rs/image#121] opened 2014-10-27 11:16 UTC
Currently, we are using the MIT license.

The difference between Apache and MIT is that Apache grants you patent licenses to use the open source.

There is a concern that we would have to check if we got the right to grant the patents when using Apache. For example, if some compression is patent protected but released under MIT, it would be permissible to use it in this library under the MIT license, but not the Apache license.

This means that in addition to receiving permission from contributors that dual license is OK, we have to check the algorithms and see what conditions they are permitted. It would be nice to do this anyway, even if we decide to stick to the MIT license.

Personally I think it is fine with MIT license. If people want to dual license, we can use the list of contributors (https://github.com/PistonDevelopers/image/graphs/contributors) subtract those who have not touched any specific algorithm and ask them to confirm the re-license.

**Comment by birktj** [comment] 2019-05-05 13:37
I am going to close this issue as being a duplicate of #503 where most of the discussion is happening.

**Closed by birktj** 2019-05-05 13:37 UTC
Labels: discussion
