### ISSUE TITLE
Support float image types

### ISSUE THREAD

**Issue by oovm** [image-rs/image#1360] opened 2020-11-14 07:05 UTC
The images in machine learning are usually stored in floating point, and the visible range is [0,1], which is equivalent to u8 [0, 255] in this interval.

When converted to u8, the part less than 0 is truncated to 0, and the part greater than 1 is truncated to 1.

Supporting this feature helps to build machine learning applications more conveniently which can avoid manual conversion back and forth.

## Draft

Add following types

```rust
pub enum DynamicImage {
    ImageLuma32(Gray32Image),
    ImageRgb32(Rgb32Image),
}

pub type Rgb32Image = ImageBuffer<Rgb<f32>, Vec<f32>>;
pub type Gray32Image = ImageBuffer<Luma<f32>, Vec<f32>>;
```

**Comment by HeroicKatora** [comment] 2020-11-14 13:08
This sounds like it should be supported to me. There are two hurdles to adoption that I see.

* Can we define sensible conversion, not only _to_ a floating point image but rather back? I suppose we can rely on the semantics of `as` casts when it comes to values that would exceed the allowed value range of `u8` or for `NaN`. That is, saturate and substitute by `0` respectively. Those semantics are guaranteed on recent Rust versions. This support is necessary for the conversion methods of the `DynamicImage` type.
* The `DynamicImage` type is an exhaustive enum. Seems like a blunder on our part. Full support for floating point images is something i'm definitely willing to make a new major version for though, it's huge :slightly_smiling_face:

**Comment by fintelia** [comment] 2020-11-14 16:09
I'm also in favor of floating point support. I think sensible conversions from float->integer might be a bit tricky because there's a couple of conventions (are the floats between 0 and 1, -1 and 1, 0 and INT_MAX?) but we can probably figure something out.

The one nit I have with the draft naming would be to include "F" somewhere in the variant names to avoid confusion with a hypothetical u32 image type.

**Comment by marcbone** [comment] 2020-12-14 14:12
it would also be nice to no not just have f32 and u32 but also f64, u16 , i32 ... basically everything that opencv has.
Also this issue is a duplicate of #795

**Comment by fintelia** [comment] 2022-07-11 17:30
Yes, [ColorType now has Rgb32F and Rgba32F variants](https://docs.rs/image/latest/image/enum.ColorType.html) with varying degrees of support from encoders/decoders. If you want to work with 32-bit integer data, I'd suggest either converting it to 16-bit, or if that's not possible, using the tiff crate which can handle it directly.

**Comment by willhansen** [comment] 2023-06-04 23:37
Next up would be `L32F` and `La32F` for symmetry?  Would be convenient.

![Selection_189](https://github.com/image-rs/image/assets/2918280/e6cec48b-c453-4098-bc1b-aa6399282326)

**Comment by fintelia** [comment] 2023-06-10 20:46
We probably won't add L32F / La32F. Every additional variant adds complexity to a bunch of places in this crate, so we'd need more justification than just symmetry.

Closing this issue because we do now support the main floating point image types

**Closed by fintelia** 2023-06-10 20:46 UTC
Labels: kind: enhancement, topic: formats

**Comment by marcbone** [comment] 2023-06-12 06:37
For the justification: L32 could represent a depth image where the pixel value would be the measured depth in meters. 

Further, I wrote a [rust version](https://crates.io/crates/rubullet) of [pybullet](https://pybullet.org/). There you can create segmentation images where each object in the scene is identified with an id that is an i32. I am using both types [here](https://github.com/neachdainn/rubullet/blob/master/rubullet/src/types.rs#L1219). I guess other people have similar use cases
