### ISSUE TITLE
Crash `memory allocation of 201863446528 bytes failed` when opening bmp file

### ISSUE THREAD

**Issue by qarmin** [image-rs/image#1535] opened 2021-08-10 20:12 UTC
Tested with image-rs 0.23.14
Just try to import [Untitled5043.bmp.zip](https://github.com/image-rs/image/files/6964271/Untitled5043.bmp.zip)
this should print this error
```
memory allocation of 201863446528 bytes failed
Aborted
```
I created this image, so feel free to use it in any way you want

**Comment by fintelia** [comment] 2021-08-10 20:25
Could you include the code you use to import the image?

**Comment by fintelia** [comment] 2021-08-10 20:29
I think this just may be a matter of not handling decoding limits yet. That should be resolved by #1445

**Comment by qarmin** [comment] 2021-08-11 04:46
By import I meant simply opening the file

**Comment by qarmin** [comment] 2021-08-11 08:15
For now I don't have test file, but looks that this also happens with `ico` images

**Comment by alexanderkjall** [comment] 2021-08-23 07:44
maybe a duplicate of: https://github.com/image-rs/image/issues/1401

**Comment by 5225225** [comment] 2021-11-02 20:51
Looks like this was indeed fixed with #1445. Though there's not a release on crates.io that contains that (pinging @HeroicKatora )

**Comment by HeroicKatora** [comment] 2021-11-02 22:14
A bit unfortunate that the fix was a while ago but we're currently pushing for the next major version, and jugling different major versions with different msrv/dependencies is too much for me to handle rn. I'm going to look into backporting bugfixes once the major version is out.

**Comment by qarmin** [comment] 2021-11-19 05:51
Is there any ETA of version 0.24.0?
I'm pinned to latest stable version of `image-rs` library so I can't use fixes directly from git.

**Closed** 2022-04-12 15:40 UTC
