### ISSUE TITLE
Crash when opening some tga files `source slice length does not match destination slice length`

### ISSUE THREAD

**Issue by qarmin** [image-rs/image#1526] opened 2021-08-03 17:23 UTC
Opening this tga files - [AAA.zip](https://github.com/image-rs/image/files/6925940/AAA.zip)
crashes library 
```
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'source slice length (1603584) does not match destination slice length (2138112)', /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/slice/mod.rs:3058:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:92:14
   2: core::slice::<impl [T]>::copy_from_slice::len_mismatch_fail
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/slice/mod.rs:3051:13
   3: core::slice::<impl [T]>::copy_from_slice
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/slice/mod.rs:3058:13
   4: <image::codecs::tga::decoder::TgaDecoder<R> as image::image::ImageDecoder>::read_image
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.23.14/./src/codecs/tga/decoder.rs:457:13
   5: image::image::decoder_to_vec
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.23.14/./src/image.rs:491:5
   6: image::dynimage::decoder_to_image
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.23.14/./src/dynimage.rs:1117:23
   7: image::dynimage::DynamicImage::from_decoder
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.23.14/./src/dynimage.rs:194:9
   8: image::io::free_functions::load
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.23.14/./src/io/free_functions.rs:75:36
   9: image::io::free_functions::open_impl
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.23.14/./src/io/free_functions.rs:48:5
  10: image::dynimage::open
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.23.14/./src/dynimage.rs:1233:5
```

**Comment by snOm3ad** [comment] 2021-08-07 17:02
After a lot of digging around I manage to find what is causing this problem. It boils down to TGA having two different file formats, the original and the new one. The specification says a TGA reader should start by finding the file footer contained in the last 26 bytes of the file and match bytes 8-23 against the string literal `"TRUEVISION-XFILE"` to determine the format of the file: `success -> new`, `fail -> original`.

The reason why this is important is because of the new format **may** contain a second header known as the *Extension Area* which has additional metadata not present in the header, see [here](https://www.fileformat.info/format/tga/egff.htm) for more info. In particular it contains `Field 24` which is the *Attributes Type* field which specifies the type of alpha channel data contained in the file.

This provides additional context to the first 4 bits of the image descriptor byte (the alpha channel bits). Including the possibility of having undefined data in the alpha channel which can be safely ignored. In other words, the value of the first 4 bits of the image descriptor field do not guarantee the presence of useful alpha channel data for the new format! 

The crash happens because the file is of the new format, and the alpha bits in the image descriptor field suggests the presence of alpha channel data, but is not checked against `Field 24` the type of data.

I don't know of a quick and easy fix for this, so I don't feel comfortable submitting a pull request without some guidance. Hope this explanation was sufficient to understand  the issue at hand!

**Comment by snOm3ad** [comment] 2021-08-08 15:02
Update: I parsed the footer and turns out the file does not contain an *Extension Area*. So the problem is definitely not what I mentioned above, but I'll leave the comment as is for anyone else looking into this.

**Comment by fintelia** [comment] 2021-08-08 18:18
So the simple approach would be to detect if we're about to overrun the buffer and return an error in that case. Would avoid the crash, but actually understanding what is going on would certainly be nicer

**Comment by snOm3ad** [comment] 2021-08-09 17:43
Right! I'll submit a draft PR right away. My initial thought was to find a way to successfully decode the image! Thanks for the help.

**Comment by snOm3ad** [comment] 2021-08-09 18:09
@fintelia I submitted the PR, please let me know if it is what you had in mind.

**Comment by fintelia** [comment] 2021-08-09 21:57
@qarmin do you know the license on those image files? It would be good to keep one around to use as a test case if the license is compatible

**Comment by qarmin** [comment] 2021-08-10 08:29
This file I copied from one of application, but not sure which exactly, so I don't think that this can be used in regression tests.
I will try to create a new image with this bug

**Closed** 2021-08-15 15:05 UTC
Labels: good first issue
