### ISSUE TITLE
JPG image first two bytes are not an SOI marker

### ISSUE THREAD

**Issue by nricciardi** [image-rs/image#2280] opened 2024-07-07 08:54 UTC
Decoding a JPG image using:

```rust
let image = ImageReader::open(src_pathbuf.clone())?.decode();
```
It returns error:  `Format error decoding Jpeg: invalid JPEG format: first two bytes are not an SOI marker`

I can open image correctly on my system.

Following the image:

![egp-igp](https://github.com/image-rs/image/assets/64961208/fdd97394-07bc-4c89-8fce-151bb185e5b7)

**Comment by fintelia** [comment] 2024-07-07 17:59
I think this is a duplicate of https://github.com/image-rs/image/issues/1233

**Closed** 2024-07-20 03:42 UTC
