### ISSUE TITLE
Do git version of image-rs use different code than in crates.io?

### ISSUE THREAD

**Issue by qarmin** [image-rs/image#1429] opened 2021-02-09 08:40 UTC
Recently I wanted to update my app to use the latest image-rs version.

After running cargo update, `image-rs` updated to version "0.23.13" and everything works fine.

But when I replace this with `image = { git = "https://github.com/image-rs/image.git", rev = "baec8513019e062bd768b026529f0acfa4054273" }`(which points to commit with release of the latest stable version of image-rs https://github.com/image-rs/image/commit/baec8513019e062bd768b026529f0acfa4054273), then I got error
```
error[E0277]: the trait bound `image::DynamicImage: Image` is not satisfied
   --> czkawka_core/src/similar_images.rs:399:46
    |
399 |                 let hash = hasher.hash_image(&image);
    |                                              ^^^^^^ the trait `Image` is not implemented for `image::DynamicImage`

```
which comes from https://github.com/abonander/img_hash library

**Comment by kaj** [comment] 2021-02-09 08:54
Hm.  `baec8513019` seems to be the merge from the release to master, the tag v0.23.13 points at `7f92e850` which is one of the parents for that release.  So that is one potential difference.  But if i do `git diff v0.23.13..baec8513019` I get nothing, so they seem to be the same.

My guess is that you have a transient dependency on the crates.io version, and then the compiler does not know that your git version and the crates.io version is the same thing, so even if all the code is exactly the same, oneimage::Image is not the same type as otherimage::Image.

**Comment by HeroicKatora** [comment] 2021-02-12 20:20
The tags should almost always point to the immediate _parent_ of the merge commit. These are also the commits that the actual release was done at. The procedure and some of its justification is described [here](https://github.com/image-rs/organization/blob/master/TASKS.md#release-procedure). Closing this as expected behavior.

**Closed by HeroicKatora** 2021-02-12 20:20 UTC
Labels: question
