### ISSUE TITLE
`load_from_memory_with_format` panics on some images

### ISSUE THREAD

**Issue by 0nkery** [image-rs/image#1165] opened 2020-03-18 18:43 UTC
This happens in v0.23.2. Binary has been built in release mode.

```
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
left: `1166400`,
right: `1183744`: destination and source slices have different lengths'
```

with the following (part of) stacktrace:

```
7: core::panicking::panic_fmt
8: <image::jpeg::decoder::JpegDecoder<R> as image::image::ImageDecoder>::read_image
9: image::image::decoder_to_vec
10: image::dynimage::DynamicImage::from_decoder
11: image::io::free_functions::load
```

I've taken a look [here](https://github.com/image-rs/image/blob/master/src/jpeg/decoder.rs#L75) (since images are mostly jpegs). Looks like it fails on `buf.copy_from_slice` since `assert` is not triggered.

## Expected

Error returned since image buffer is invalid.

## Actual behaviour

Panic.

## Reproduction steps

Sorry, I don't have an image to reproduce this panic.

**Comment by HeroicKatora** [comment] 2020-03-18 19:34
Possibly a duplicate of #1157. The backtrace is much nicer with the new Rust version though.

**Comment by 0nkery** [comment] 2020-03-18 19:59
Yep, I think so. Feel free to incorporate this issue into existing one and close it.

**Comment by HeroicKatora** [comment] 2020-03-18 20:10
@0nkery You could help me if you could find the _actual_ image dimensions of the image that fails to be loaded here.

**Comment by HeroicKatora** [comment] 2020-03-18 20:12
As well as any other meta data you can find/disclose, like color types and more.

**Comment by 0nkery** [comment] 2020-03-19 13:10
```
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
left: `1105920`,
right: `1114112`: destination and source slices have different lengths',
```

[Image](https://sun1-86.userapi.com/c855620/v855620019/2085f3/ZJ3BTtNqHZk.jpg)
that triggered this panic.

**Comment by lovasoa** [comment] 2020-04-25 17:57
Could someone replicate this bug ? Just as with #1157, I cannot replicate it. The image (sha1: d7a79285798269998fb36736cd0ff80cda4b29e7) can be opened with image-rs without problems. 
And just like #1157, converting the image to greyscale with a 2x2 sampling factor triggers image-rs/jpeg-decoder#148

However, in this case, the buffer sizes are not consistent with what was reported: neither

```
left: `1105920`,
right: `1114112`
```

nor

```
left: `1166400`,
right: `1183744`
```

**Comment by HeroicKatora** [comment] 2020-06-20 06:23
#1157 was marked fixed. This was likely the same and since no reproduction was provided it's not any more actionable. Closing this.

**Closed by HeroicKatora** 2020-06-20 06:23 UTC
Labels: bug
